/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsResultsRouteImport } from './routes/events.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsResultsRoute = EventsResultsRouteImport.update({
  id: '/events/results',
  path: '/events/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filters': typeof FiltersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/results': typeof EventsResultsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filters': typeof FiltersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/results': typeof EventsResultsRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filters': typeof FiltersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/results': typeof EventsResultsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/filters' | '/events/$eventId' | '/events/results' | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filters' | '/events/$eventId' | '/events/results' | '/events'
  id:
    | '__root__'
    | '/'
    | '/filters'
    | '/events/$eventId'
    | '/events/results'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FiltersRoute: typeof FiltersRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsResultsRoute: typeof EventsResultsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/results': {
      id: '/events/results'
      path: '/events/results'
      fullPath: '/events/results'
      preLoaderRoute: typeof EventsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FiltersRoute: FiltersRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsResultsRoute: EventsResultsRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
